INFO:     Started server process [9776]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8003 (Press CTRL+C to quit)
[32m2025-10-08 12:15:26.087[0m | [1mINFO    [0m | [36mrunner.workflow_runner[0m:[36mexecute_workflow[0m:[36m139[0m - [1m执行节点: 文件转图片[0m
[32m2025-10-08 12:15:26.708[0m | [34m[1mDEBUG   [0m | [36mrunner.component_executor[0m:[36m_run_subprocess[0m:[36m171[0m - [34m[1m子进程 stdout:
EXECUTION_ERROR: 组件执行失败: Traceback (most recent call last):
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\base.py", line 476, in execute
    result = self.run(validated_params, validated_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\数据转换\087e42e1-bf58-4acd-a99a-3dd4d0013dca.py", line 39, in run
    "image": Image.open(inputs.get("file"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\envs\miniconda\envs\3.11\Lib\site-packages\PIL\Image.py", line 3513, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

[0m
[32m2025-10-08 12:15:26.718[0m | [31m[1mERROR   [0m | [36mrunner.workflow_runner[0m:[36mexecute_workflow[0m:[36m149[0m - [31m[1m节点执行失败 文件转图片: 组件执行失败: 组件执行失败: Traceback (most recent call last):
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\base.py", line 476, in execute
    result = self.run(validated_params, validated_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\数据转换\087e42e1-bf58-4acd-a99a-3dd4d0013dca.py", line 39, in run
    "image": Image.open(inputs.get("file"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\envs\miniconda\envs\3.11\Lib\site-packages\PIL\Image.py", line 3513, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

Traceback (most recent call last):
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\base.py", line 476, in execute
    result = self.run(validated_params, validated_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\数据转换\087e42e1-bf58-4acd-a99a-3dd4d0013dca.py", line 39, in run
    "image": Image.open(inputs.get("file"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\envs\miniconda\envs\3.11\Lib\site-packages\PIL\Image.py", line 3513, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\black\AppData\Local\Temp\tmpzdxcb2pb.py", line 43, in <module>
    output = comp_instance.execute(params, inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\base.py", line 501, in execute
    raise ComponentError(error_msg, "EXECUTION_ERROR")
base.ComponentError: 组件执行失败: Traceback (most recent call last):
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\base.py", line 476, in execute
    result = self.run(validated_params, validated_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\数据转换\087e42e1-bf58-4acd-a99a-3dd4d0013dca.py", line 39, in run
    "image": Image.open(inputs.get("file"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\envs\miniconda\envs\3.11\Lib\site-packages\PIL\Image.py", line 3513, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

[0m
[32m2025-10-08 12:15:26.719[0m | [31m[1mERROR   [0m | [36mrunner.workflow_runner[0m:[36mexecute_workflow[0m:[36m151[0m - [31m[1mTraceback (most recent call last):
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\runner\workflow_runner.py", line 140, in execute_workflow
    output = run_component_in_subprocess(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\runner\component_executor.py", line 82, in run_component_in_subprocess
    raise RuntimeError(f"组件执行失败: {error_info['error']}\n{error_info['traceback']}")
RuntimeError: 组件执行失败: 组件执行失败: Traceback (most recent call last):
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\base.py", line 476, in execute
    result = self.run(validated_params, validated_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\数据转换\087e42e1-bf58-4acd-a99a-3dd4d0013dca.py", line 39, in run
    "image": Image.open(inputs.get("file"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\envs\miniconda\envs\3.11\Lib\site-packages\PIL\Image.py", line 3513, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

Traceback (most recent call last):
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\base.py", line 476, in execute
    result = self.run(validated_params, validated_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\数据转换\087e42e1-bf58-4acd-a99a-3dd4d0013dca.py", line 39, in run
    "image": Image.open(inputs.get("file"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\envs\miniconda\envs\3.11\Lib\site-packages\PIL\Image.py", line 3513, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\black\AppData\Local\Temp\tmpzdxcb2pb.py", line 43, in <module>
    output = comp_instance.execute(params, inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\base.py", line 501, in execute
    raise ComponentError(error_msg, "EXECUTION_ERROR")
base.ComponentError: 组件执行失败: Traceback (most recent call last):
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\base.py", line 476, in execute
    result = self.run(validated_params, validated_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\projects\图像分类(含4通道转3通道)\components\数据转换\087e42e1-bf58-4acd-a99a-3dd4d0013dca.py", line 39, in run
    "image": Image.open(inputs.get("file"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\WorkFlowGUI\envs\miniconda\envs\3.11\Lib\site-packages\PIL\Image.py", line 3513, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''


[0m
[32m2025-10-08 12:15:26.719[0m | [1mINFO    [0m | [36mrunner.workflow_runner[0m:[36mexecute_workflow[0m:[36m139[0m - [1m执行节点: 图像4通道转3通道[0m
[32m2025-10-08 12:15:27.379[0m | [33m[1mWARNING [0m | [36mrunner.component_executor[0m:[36m_run_subprocess[0m:[36m173[0m - [33m[1m子进程 stderr:
[32m2025-10-08 12:15:27.269[0m | [1mINFO    [0m | [36m__main__[0m:[36minfo[0m:[36m26[0m - [1m(1024, 1024, 3)[0m
[32m2025-10-08 12:15:27.332[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36msuccess[0m:[36m27[0m - [32m[1m执行完成[0m
[0m
[32m2025-10-08 12:15:27.385[0m | [1mINFO    [0m | [36mrunner.workflow_runner[0m:[36mexecute_workflow[0m:[36m139[0m - [1m执行节点: 图像分类测试[0m
[32m2025-10-08 12:15:30.257[0m | [33m[1mWARNING [0m | [36mrunner.component_executor[0m:[36m_run_subprocess[0m:[36m173[0m - [33m[1m子进程 stderr:
[32m2025-10-08 12:15:29.801[0m | [1mINFO    [0m | [36m__main__[0m:[36minfo[0m:[36m26[0m - [1mModel loaded on cpu[0m
[32m2025-10-08 12:15:29.996[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36msuccess[0m:[36m27[0m - [32m[1m执行完成[0m
[0m
[32m2025-10-08 12:15:30.264[0m | [1mINFO    [0m | [36m__main__[0m:[36mrun_workflow[0m:[36m100[0m - [1m工作流执行成功，结果：{'predict_class': 'digital clock', 'confidence': 0.857114315032959, 'model': 'C:\\Users\\black\\AppData\\Local\\Temp\\tmpfoybhh_y.pth'}[0m
INFO:     127.0.0.1:52180 - "POST /run HTTP/1.1" 200 OK
[32m2025-10-08 12:16:06.025[0m | [1mINFO    [0m | [36mrunner.workflow_runner[0m:[36mexecute_workflow[0m:[36m139[0m - [1m执行节点: 文件转图片[0m
[32m2025-10-08 12:16:06.852[0m | [33m[1mWARNING [0m | [36mrunner.component_executor[0m:[36m_run_subprocess[0m:[36m173[0m - [33m[1m子进程 stderr:
[32m2025-10-08 12:16:06.807[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36msuccess[0m:[36m27[0m - [32m[1m执行完成[0m
[0m
[32m2025-10-08 12:16:06.858[0m | [1mINFO    [0m | [36mrunner.workflow_runner[0m:[36mexecute_workflow[0m:[36m139[0m - [1m执行节点: 图像4通道转3通道[0m
[32m2025-10-08 12:16:07.652[0m | [33m[1mWARNING [0m | [36mrunner.component_executor[0m:[36m_run_subprocess[0m:[36m173[0m - [33m[1m子进程 stderr:
[32m2025-10-08 12:16:07.450[0m | [1mINFO    [0m | [36m__main__[0m:[36minfo[0m:[36m26[0m - [1m(2037, 3832, 3)[0m
[32m2025-10-08 12:16:07.605[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36msuccess[0m:[36m27[0m - [32m[1m执行完成[0m
[0m
[32m2025-10-08 12:16:07.658[0m | [1mINFO    [0m | [36mrunner.workflow_runner[0m:[36mexecute_workflow[0m:[36m139[0m - [1m执行节点: 图像分类测试[0m
[32m2025-10-08 12:16:10.522[0m | [33m[1mWARNING [0m | [36mrunner.component_executor[0m:[36m_run_subprocess[0m:[36m173[0m - [33m[1m子进程 stderr:
[32m2025-10-08 12:16:10.041[0m | [1mINFO    [0m | [36m__main__[0m:[36minfo[0m:[36m26[0m - [1mModel loaded on cpu[0m
[32m2025-10-08 12:16:10.262[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36msuccess[0m:[36m27[0m - [32m[1m执行完成[0m
[0m
[32m2025-10-08 12:16:10.528[0m | [1mINFO    [0m | [36m__main__[0m:[36mrun_workflow[0m:[36m100[0m - [1m工作流执行成功，结果：{'predict_class': 'radio', 'confidence': 0.2753298580646515, 'model': 'C:\\Users\\black\\AppData\\Local\\Temp\\tmplbal5wgr.pth'}[0m
INFO:     127.0.0.1:52230 - "POST /run HTTP/1.1" 200 OK
